import React, { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Search, ShieldCheck, TrendingUp, AlertTriangle, Database, SlidersHorizontal, ExternalLink, BarChart3 } from "lucide-react";

const stocks = [
  { rank: 1, ticker: "SOFI", company: "SoFi Technologies", price: 17.93, tier: "Primary", grade: "A", score: 91, role: "Best total accumulation profile", thesis: "CEO open-market buying, strong platform growth, positive net income, and favorable institutional inflow/outflow profile.", risk: "Medium", insiderSignal: "Positive", institutionalSignal: "Positive", action: "Core accumulation candidate", allocation: 22 },
  { rank: 2, ticker: "CELH", company: "Celsius Holdings", price: 29.42, tier: "Primary", grade: "A-", score: 88, role: "Strong insider-buying signal", thesis: "Recent insider cluster buying, strong revenue growth, positive earnings, and rebound potential after weakness.", risk: "Medium", insiderSignal: "Positive", institutionalSignal: "Mixed", action: "Accumulation candidate", allocation: 18 },
  { rank: 3, ticker: "TOST", company: "Toast", price: 28.25, tier: "Primary", grade: "A-", score: 86, role: "Institutional-quality growth platform", thesis: "High institutional ownership, positive net income, ARR growth, margin expansion, and platform durability in restaurant/retail payments.", risk: "Medium", insiderSignal: "Neutral", institutionalSignal: "Positive", action: "Accumulation candidate", allocation: 16 },
  { rank: 4, ticker: "UBER", company: "Uber Technologies", price: 72.16, tier: "Primary", grade: "B+", score: 83, role: "Profitable mature platform under $100", thesis: "Large profitable platform, strong institutional ownership, free cash flow expansion, and analyst support.", risk: "Medium-Low", insiderSignal: "Neutral", institutionalSignal: "Positive", action: "Mature platform candidate", allocation: 14 },
  { rank: 5, ticker: "WK", company: "Workiva", price: 48.79, tier: "Secondary", grade: "B", score: 79, role: "Software recovery candidate", thesis: "High institutional ownership, strong retention, improving profitability, AI-enabled reporting platform, and analyst upside.", risk: "Medium", insiderSignal: "Neutral", institutionalSignal: "Mixed", action: "Secondary accumulation candidate", allocation: 10 },
  { rank: 6, ticker: "OSCR", company: "Oscar Health", price: 28.52, tier: "Watch", grade: "B-", score: 74, role: "Healthcare growth candidate", thesis: "Strong revenue scale and institutional inflows, but large recent insider selling reduces quality score.", risk: "Medium-High", insiderSignal: "Negative", institutionalSignal: "Positive", action: "Watch only until insider pressure cools", allocation: 6 },
  { rank: 7, ticker: "ASTS", company: "AST SpaceMobile", price: 87.66, tier: "Watch", grade: "B-", score: 73, role: "High-upside asymmetric candidate", thesis: "Strong institutional inflows and large market potential, but insider selling and cash-burn risk require caution.", risk: "High", insiderSignal: "Negative", institutionalSignal: "Positive", action: "High-risk watchlist", allocation: 5 },
  { rank: 8, ticker: "CIFR", company: "Cipher Digital", price: 24.5, tier: "Watch", grade: "C+", score: 69, role: "Infrastructure rerating candidate", thesis: "AI/HPC/data-center theme and institutional additions exist, but insider selling and negative earnings keep risk elevated.", risk: "High", insiderSignal: "Negative", institutionalSignal: "Positive", action: "Speculative watchlist", allocation: 4 },
  { rank: 9, ticker: "APLD", company: "Applied Digital", price: 37.3, tier: "Watch", grade: "C+", score: 67, role: "AI infrastructure risk/reward", thesis: "Strong AI infrastructure theme and institutional additions, but insider selling, debt, losses, and customer concentration are major flags.", risk: "High", insiderSignal: "Negative", institutionalSignal: "Positive", action: "Speculative watchlist", allocation: 3 },
  { rank: 10, ticker: "BTSG", company: "BrightSpring Health Services", price: 69.74, tier: "Watch", grade: "C", score: 64, role: "Healthcare services momentum", thesis: "Strong operating momentum, but sponsor/management secondary selling lowers accumulation quality.", risk: "Medium-High", insiderSignal: "Negative", institutionalSignal: "Mixed", action: "Watch only after secondary pressure clears", allocation: 2 }
];

const scoreWeights = [
  ["Revenue acceleration", 20], ["Margin / profitability trend", 15], ["Institutional accumulation", 15],
  ["Balance-sheet survival", 15], ["Dilution control", 10], ["Catalyst strength", 15], ["Valuation upside", 10]
];

const colors = {
  bg: "#020617", panel: "rgba(15,23,42,.88)", border: "#1e293b", muted: "#94a3b8", text: "#f8fafc", cyan: "#22d3ee", green: "#86efac", amber: "#fcd34d"
};

function gradeStyle(grade){ return { background: grade.startsWith("A") ? "#059669" : grade.startsWith("B") ? "#2563eb" : "#d97706", color: "white" }; }
function signalStyle(signal){ return signal === "Positive" ? {background:"#dcfce7", color:"#166534"} : signal === "Negative" ? {background:"#fee2e2", color:"#991b1b"} : {background:"#e2e8f0", color:"#334155"}; }
function Card({children, style={}}){ return <div style={{border:`1px solid ${colors.border}`, background:colors.panel, borderRadius:18, padding:18, ...style}}>{children}</div>; }
function Pill({children, style={}}){ return <span style={{display:"inline-flex", borderRadius:999, padding:"5px 9px", fontSize:12, fontWeight:800, ...style}}>{children}</span>; }

export default function App(){
  const [query,setQuery]=useState(""); const [tier,setTier]=useState("All"); const [sortBy,setSortBy]=useState("rank"); const [selected,setSelected]=useState(stocks[0]);
  const filtered = useMemo(()=> stocks.filter(s => (`${s.ticker} ${s.company} ${s.role} ${s.thesis}`).toLowerCase().includes(query.toLowerCase()) && (tier==="All"||s.tier===tier)).sort((a,b)=> sortBy==="score"?b.score-a.score:sortBy==="price"?a.price-b.price:sortBy==="allocation"?b.allocation-a.allocation:a.rank-b.rank), [query,tier,sortBy]);
  const primary = stocks.filter(s=>s.tier==="Primary").reduce((a,s)=>a+s.allocation,0);
  const watch = stocks.filter(s=>s.tier==="Watch").reduce((a,s)=>a+s.allocation,0);

  return <div style={{minHeight:"100vh", background:colors.bg, color:colors.text, fontFamily:"Inter, system-ui, sans-serif"}}>
    <div style={{maxWidth:1280, margin:"0 auto", padding:24}}>
      <motion.div initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.4}}>
        <div style={{display:"grid", gridTemplateColumns:"1.2fr 1fr", gap:24, alignItems:"end"}} className="hero-grid">
          <div>
            <div style={{display:"inline-flex", gap:8, alignItems:"center", border:"1px solid rgba(34,211,238,.35)", background:"rgba(34,211,238,.1)", color:"#a5f3fc", padding:"7px 11px", borderRadius:999, fontSize:13, marginBottom:14}}><ShieldCheck size={16}/>Software-Grade Accumulation Intelligence</div>
            <h1 style={{fontSize:44, lineHeight:1.05, margin:0}}>Accumulation Intelligence Dashboard</h1>
            <p style={{color:"#cbd5e1", lineHeight:1.65}}>Website-ready dashboard for ranking under-$100 accumulation candidates using fundamentals, institutional flow, insider activity, dilution risk, catalyst quality, and price accessibility.</p>
          </div>
          <div style={{display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12}} className="metrics-grid">
            <Metric label="Candidates" value="10"/><Metric label="Primary Weight" value={`${primary}%`} color={colors.green}/><Metric label="Watch Weight" value={`${watch}%`} color={colors.amber}/><Metric label="Top Grade" value="A" color="#67e8f9"/>
          </div>
        </div>
      </motion.div>
      <Card style={{margin:"24px 0"}}><div style={{display:"grid", gridTemplateColumns:"1.5fr 1fr 1fr", gap:12}} className="filter-grid"><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:12,top:13,color:colors.muted}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker, company, thesis..." style={input({paddingLeft:38})}/></div><select value={tier} onChange={e=>setTier(e.target.value)} style={input()}><option>All</option><option>Primary</option><option>Secondary</option><option>Watch</option></select><select value={sortBy} onChange={e=>setSortBy(e.target.value)} style={input()}><option value="rank">Sort by rank</option><option value="score">Sort by score</option><option value="price">Sort by price</option><option value="allocation">Sort by model weight</option></select></div></Card>
      <div style={{display:"grid", gridTemplateColumns:"2fr 1fr", gap:24}} className="main-grid">
        <div style={{display:"grid", gap:12}}>{filtered.map(s=><StockRow key={s.ticker} stock={s} selected={selected.ticker===s.ticker} onClick={()=>setSelected(s)}/>)}</div>
        <div style={{display:"grid", gap:18, alignContent:"start"}}><Selected selected={selected}/><Scoring/><Protocol/></div>
      </div>
      <Card style={{marginTop:24}}><h3 style={{margin:0}}>Next Engineering Step</h3><p style={{color:"#cbd5e1"}}>Upgrade this prototype into a production service with live market data, SEC EDGAR ingestion, user accounts, watchlists, alerts, and historical score tracking.</p><button style={{border:`1px solid #334155`, background:colors.bg, color:colors.text, borderRadius:12, padding:"12px 16px", display:"flex", gap:8, alignItems:"center", cursor:"pointer"}}><ExternalLink size={16}/>Export Spec</button></Card>
    </div>
    <style>{`@media(max-width:950px){.hero-grid,.main-grid{grid-template-columns:1fr!important}.metrics-grid{grid-template-columns:repeat(2,1fr)!important}.filter-grid{grid-template-columns:1fr!important}}`}</style>
  </div>;
}

function Metric({label,value,color="white"}){return <Card style={{padding:14}}><p style={{margin:0,color:colors.muted,fontSize:12}}>{label}</p><p style={{margin:"6px 0 0",fontSize:26,fontWeight:800,color}}>{value}</p></Card>}
function input(extra={}){return {width:"100%",height:42,border:"1px solid #334155",background:colors.bg,color:colors.text,borderRadius:12,padding:"0 12px",outline:"none",boxSizing:"border-box",...extra};}
function StockRow({stock,selected,onClick}){return <motion.button onClick={onClick} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} style={{width:"100%",textAlign:"left",border:selected?`1px solid ${colors.cyan}`:`1px solid ${colors.border}`,background:selected?"rgba(34,211,238,.1)":colors.panel,color:colors.text,borderRadius:18,padding:18,cursor:"pointer"}}><div style={{display:"grid", gridTemplateColumns:"1.5fr 1fr", gap:14, alignItems:"center"}}><div style={{display:"flex",gap:14,alignItems:"center"}}><div style={{height:44,width:44,borderRadius:14,background:colors.bg,color:"#67e8f9",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800}}>#{stock.rank}</div><div><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><strong style={{fontSize:18}}>{stock.ticker}</strong><span style={{color:colors.muted,fontSize:14}}>{stock.company}</span><Pill style={gradeStyle(stock.grade)}>{stock.grade}</Pill></div><p style={{margin:"5px 0 0",color:"#cbd5e1",fontSize:14}}>{stock.role}</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,textAlign:"right"}}><Mini label="Price" value={`$${stock.price.toFixed(2)}`}/><Mini label="Score" value={stock.score} color="#67e8f9"/><Mini label="Model" value={`${stock.allocation}%`} color={colors.green}/></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><Pill style={{border:"1px solid #334155",background:colors.bg,color:"#cbd5e1"}}>{stock.tier}</Pill><Pill style={{border:"1px solid #334155",background:colors.bg,color:"#cbd5e1"}}>Risk: {stock.risk}</Pill><Pill style={signalStyle(stock.insiderSignal)}>Insider: {stock.insiderSignal}</Pill><Pill style={signalStyle(stock.institutionalSignal)}>Institutional: {stock.institutionalSignal}</Pill></div></motion.button>}
function Mini({label,value,color="white"}){return <div><p style={{margin:0,color:"#64748b",fontSize:12}}>{label}</p><p style={{margin:"4px 0 0",color,fontWeight:800}}>{value}</p></div>}
function Selected({selected}){return <Card><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><p style={{margin:0,color:colors.muted,fontSize:13}}>Selected Candidate</p><h2 style={{margin:"5px 0 0",fontSize:28}}>{selected.ticker}</h2><p style={{margin:"4px 0 0",color:colors.muted}}>{selected.company}</p></div><Pill style={{...gradeStyle(selected.grade),height:"fit-content"}}>{selected.grade}</Pill></div><div style={{height:12,borderRadius:999,background:"#1e293b",margin:"18px 0"}}><div style={{height:"100%",width:`${selected.score}%`,borderRadius:999,background:colors.cyan}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}><Info label="Price" value={`$${selected.price.toFixed(2)}`}/><Info label="Score" value={`${selected.score}/100`} color="#67e8f9"/><Info label="Model" value={`${selected.allocation}%`} color={colors.green}/></div><Block icon={<TrendingUp size={17} color="#67e8f9"/>} title="Thesis">{selected.thesis}</Block><Block icon={<AlertTriangle size={17} color={colors.amber}/>} title="Action">{selected.action}</Block></Card>}
function Info({label,value,color="white"}){return <div style={{background:colors.bg,borderRadius:14,padding:12}}><p style={{margin:0,color:"#64748b",fontSize:12}}>{label}</p><p style={{margin:"6px 0 0",color,fontWeight:800}}>{value}</p></div>}
function Block({icon,title,children}){return <div style={{marginTop:16,border:`1px solid ${colors.border}`,background:colors.bg,borderRadius:16,padding:14}}><p style={{margin:"0 0 8px",display:"flex",alignItems:"center",gap:8,fontWeight:800}}>{icon}{title}</p><p style={{margin:0,color:"#cbd5e1",lineHeight:1.65,fontSize:14}}>{children}</p></div>}
function Scoring(){return <Card><p style={{margin:"0 0 14px",display:"flex",alignItems:"center",gap:8}}><SlidersHorizontal size={17} color="#67e8f9"/><strong>Scoring Model</strong></p>{scoreWeights.map(([label,weight])=><div key={label} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12}}><span style={{color:"#cbd5e1"}}>{label}</span><span style={{color:colors.muted}}>{weight}%</span></div><div style={{height:8,borderRadius:999,background:"#1e293b",marginTop:6}}><div style={{height:"100%",width:`${weight*5}%`,borderRadius:999,background:"#06b6d4"}}/></div></div>)}</Card>}
function Protocol(){return <Card><p style={{margin:"0 0 14px",display:"flex",alignItems:"center",gap:8}}><Database size={17} color="#67e8f9"/><strong>Data Protocol</strong></p><ol style={{margin:0,paddingLeft:20,color:"#cbd5e1",lineHeight:1.8,fontSize:14}}><li>Price and fundamentals refresh.</li><li>Form 13F institutional flow check.</li><li>Form 4 insider transaction check.</li><li>10-Q / 10-K risk review.</li><li>Dilution, secondary offering, and debt review.</li><li>Final grade and model-weight update.</li></ol><button style={{marginTop:16,width:"100%",border:"none",background:colors.cyan,color:colors.bg,padding:"12px 14px",borderRadius:12,fontWeight:800,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:8}}><BarChart3 size={16}/>Ready for Website Buildout</button></Card>}
